# Generated by Django 4.0.1 on 2022-01-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('movie_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='genre.genre')),
                ('members', models.ManyToManyField(related_name='movies', to='movie_member.MovieMember')),
            ],
        ),
    ]
