# Generated by Django 4.0.1 on 2022-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('rol', models.CharField(choices=[('1', 'Actor/Actress'), ('2', 'Director'), ('3', 'Producer')], max_length=1, verbose_name='rol')),
            ],
        ),
    ]
